package com.example.overdex.model

import java.util.UUID

/**
 * Defines the semantic categories of events that can occur during a battle.
 */
enum class BattleEventType {
    /** The overall battle session has started. */
    BATTLE_STARTED,
    /** The overall battle session has concluded. */
    BATTLE_ENDED,
    /** A specific Pokémon has been identifying on the screen. */
    POKEMON_IDENTIFIED,
    /** A trainer has swapped their active Pokémon. */
    POKEMON_SWITCHED,
    /** A Pokémon's HP has reached zero. */
    POKEMON_FAINTED,
    /** A charged move animation or damage event was detected. */
    CHARGED_MOVE_THROWN,
    /** A shield deployment was detected. */
    SHIELD_USED,
    /** The estimated or observed energy level of a Pokémon was updated. */
    ENERGY_UPDATED
}

/**
 * Identifies the participant responsible for an event.
 */
enum class BattleActor {
    /** The player using the Overdex instrument. */
    PLAYER,
    /** The opponent trainer. */
    ENEMY,
    /** An event generated by the Overdex system itself. */
    SYSTEM
}

/**
 * A discrete factual occurrence in a battle's history.
 * 
 * @property id Unique identifier for the event.
 * @property timestamp Absolute system time in ms.
 * @property type The kind of event that occurred.
 * @property actor The trainer or system that performed the action.
 * @property pokemonId The Pokédex ID of the Pokémon involved (if applicable).
 * @property value A generic numerical value associated with the event (e.g., energy level).
 * @property message A human-readable description of the event.
 * @property confidence The system's certainty regarding this event.
 */
data class BattleEvent(
    val id: String = UUID.randomUUID().toString(),
    val timestamp: Long = System.currentTimeMillis(),
    val type: BattleEventType,
    val actor: BattleActor = BattleActor.SYSTEM,
    val pokemonId: Int? = null, // Use Stable IDs (#006) instead of Strings
    val value: Int? = null,
    val message: String? = null,
    val confidence: Confidence = Confidence(ConfidenceLevel.OBSERVED)
)
