package com.example.overdex.ui.components

enum class CalibrationRegion {
    NONE,
    ENEMY_NAME,
    HP_BAR,
    TEAM_ICONS,
    MOVE_BANNER,
    OPPONENT_SHIELDS,
    YOU_WIN,
    GOOD_EFFORT,
    COUNTDOWN,
    ANNOUNCEMENT,
    TRAINER_TEAM_INFO,
    OPPONENT_TEAM_INFO,
    TRAINER_ACTIVE_TYPE,
    OPPONENT_ACTIVE_TYPE,
    TRAINER_HP,
    OPPONENT_HP,
    CHARGE_MOVE_EXECUTION,
    TRAINER_CHARGE_MOVE_CONTROLS,
    TRAINER_INACTIVE_POKEMON,
    MATCH_OUTCOME
}
